### PR TITLE
Add reachestimate for Ad Account

### PR DESCRIPTION
**Pull request by icole**
I have a need to query `/reachestimate` for a particular ad account (https://developers.facebook.com/docs/marketing-api/reference/ad-account/reachestimate/v2.8).

One issue I had was with several dependencies on the `activesupport` gem so I added that as a gem dependency, since right now I am running it outside of a Rails project.

Please critic and let me know if I missed the mark on anything!

### CODE REVIEW

**Comment by cte** [comment]
Thanks for the PR. Will check it out shortly.

**Comment by cte** [comment]
Added here: https://github.com/cte/facebook-ruby-ads-sdk/commit/ae35878e584ceb4d18ea353cfe7f658f54d7d85f

I prefer not to depend on `active_support` in this gem.

**Comment by icole** [comment]
@cte, Understandable, FYI I would have happily refactored out the active support stuff if you had asked. I was really hoping to get more public code contributions on my GitHub. Thanks for implementing anyway

**Comment by cte** [comment]
That's awesome thanks!

Here you go: https://github.com/cte/facebook-ruby-ads-sdk/pull/9

**Pull request closed without merging**
